# Generated by Django 5.2.6 on 2025-09-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
    ]
