# Generated by Django 5.2.6 on 2025-09-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='description',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
